[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]
  [mediaTypes."text/gemini"]
    suffixes = ["gmi"]

[outputFormats]
  [outputFormats.Atom]
    mediaType = "application/atom+xml"
    baseName = "atom"
  [outputFormats.Gemini]
    mediaType = "text/gemini"
    isPlainText = true # Disable HTML renderer
    isHTML = false # Disable LiveReload, alias redirect, etc.
    permalinkable = true
    protocol = "gemini://"
  [outputFormats.Gemini_Atom]
    mediaType = "application/atom+xml"
    baseName = "atom"
    protocol = "gemini://"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
    [markup.goldmark.extensions]
      linkify = false
